In [2]:
import pandas as pd
import numpy as np

In [2]:
# Data read
# 어획량 Data
fish_catch = pd.read_csv('data/어획량(전처리).csv')
# 방류 Data
fish_discharge = pd.read_csv('data/방류실적(전처리).csv')

In [3]:
# merge
merged_data = pd.merge(fish_catch, fish_discharge, on=['시도', '어종류', '연도', '월'], how='outer')

# DataFrame 
fish_data = pd.DataFrame(merged_data)

# index set
fish_data = fish_data.set_index('시도')

# drop columns
fish_data = fish_data.drop(columns=['Unnamed: 0'], axis=1)

# column 조정
fish_col = fish_data.set_axis(['어종류', '연도', '월', '어획량_마리', '어획량_Kg', '품종', '방류량', '방류구분'], axis=1)

# 특정 column 행 결측치 처리
columns_tf = ['어획량_마리', '어획량_Kg', '방류량']
columns_tf1 = ['품종', '방류구분']
fish_col[columns_tf] = fish_col[columns_tf].fillna(0.0)
fish_col[columns_tf1] = fish_col[columns_tf1].fillna('미방류')

fish_col

     어종류    연도   월  어획량_마리  어획량_Kg     품종       방류량  방류구분
시도
강원  가자미류  2022   7     0.0     0.0   강도다리   94783.0  매입방류
강원  가자미류  2022   7     0.0     0.0  문치가자미   92986.0  매입방류
강원  가자미류  2022   8     0.0     0.0   강도다리  137218.0  매입방류
강원  가자미류  2022   8     0.0     0.0   강도다리   34058.0  매입방류
강원  가자미류  2022   8     0.0     0.0   강도다리   35581.0  매입방류
..   ...   ...  ..     ...     ...    ...       ...   ...
충남    해삼  2024   6     0.0     0.0    미방류       0.0   미방류
충남    해삼  2024   7     0.0     0.0    미방류       0.0   미방류
충남    해삼  2024   8     0.0     0.0    미방류       0.0   미방류
충남    해삼  2024   9     0.0     0.0    미방류       0.0   미방류
충남    해삼  2024  10     0.0     0.0    미방류       0.0   미방류

[6637 rows x 8 columns]

In [9]:
fish = fish_col.dropna(subset=['어획량_마리', '어획량_Kg'])
fish

array([     0., 304982., 628437., ...,   4478.,  13931.,   5723.])

In [6]:
fish.to_csv('data/어획_방류.csv', index=True)